[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.1"
axum-extra = { version = "0.2.1", features = ["spa"] }
clap = { version = "3.1.8", features = ["derive"] }
log = "0.4.16"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.2.5", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
